apiVersion: v1
kind: ConfigMap
metadata:
  name: nutrition-config
  namespace: nutrition-feedback
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  POSTGRES_DB: "nutrition_feedback"
  POSTGRES_USER: "nutrition_user"
  REDIS_URL: "redis://nutrition-redis:6379"
  PROMETHEUS_METRICS_PORT: "9090"
---
apiVersion: v1
kind: Secret
metadata:
  name: nutrition-secrets
  namespace: nutrition-feedback
type: Opaque
stringData:
  POSTGRES_PASSWORD: "your-secure-password-here"
  JWT_SECRET_KEY: "your-jwt-secret-here"
  SENTRY_DSN: "your-sentry-dsn-here"